name: DockerReleasing
on:
  push:

env:
  GH_USER: ${{ github.actor }}

jobs:
  docker:
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
    
    steps:
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GH_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: "Set build date"
        id: build_date
        run: echo "::set-output name=builddate::$(date -Isec)"
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            BUILD_DATE=${{ steps.build_date.outputs.builddate }}
            GH_USER_ARG=${{ env.GH_USER }}
          push: true
          tags: ghcr.io/${{ env.GH_USER }}/kubectl-slice:latest
